name: pytest
on:
  push:
  #  branches: [master]
  pull_request:
    branches: [master]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --user aiohttp mock pytest warcio
      - run: pytest
