name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.8', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup
        with:
          python-version: ${{ matrix.version }}

      - name: Run tests
        run: |
          uv run py.test --tb=native --verbose tests/test_certauth.py tests/test_dedup.py tests/test_warcprox.py tests/test_writer.py
